server:
  port: 8081
# MySQL - 8.0.28
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.92.160:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    # ?????? druid
    type: com.alibaba.druid.pool.DruidDataSource
    # druid??
    druid:
      # ????????
      initial-size: 5
      # ?????
      max-active: 20
      # ?????
      min-idle: 1
      # ??????
      max-wait: 60000
# mybatis??
mybatis:
  #  ??xml??
  mapper-locations: "classpath*:mapper/*.xml"
  #  ??model???
  type-aliases-package: "com.henggao.cmlakehouse.entity.*"
